'stage0':
    - changed-files:
          - any-glob-to-any-file:
                [
                    examples/stage0/**,
                    src/content/docs/learning-course/intro-to-java/**,
                ]
'stage1':
    - changed-files:
          - any-glob-to-any-file: examples/stage1/**
'examples':
    - changed-files:
          - any-glob-to-any-file: examples/**
