import { execSync } from 'child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';
import { glossaryTerms } from '../src/data/glossary';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const OUTPUT = resolve(ROOT, 'src/content/docs/resources/glossary.mdx');
const CHECK = process.argv.includes('--check');

const sorted = [...glossaryTerms].sort((a, b) =>
    a.term.toLowerCase().localeCompare(b.term.toLowerCase()),
);

const frontmatter = ['---', 'title: Glossary', '---'];

const body = [
    '{/* This file is auto-generated by scripts/generate-glossary.ts. Do not edit directly. */}',
    '',
    '',
];

for (const { term, definition } of sorted) {
    body.push(`**${term}**`);
    body.push('');
    body.push(`${definition}`);
    body.push('');
}

const content = [...frontmatter, '', ...body].join('\n');

function formatFile(filePath: string) {
    execSync(`pnpm prettier --write "${filePath}"`, {
        cwd: ROOT,
        stdio: 'pipe',
    });
}

if (CHECK) {
    const existing = readFileSync(OUTPUT, 'utf-8');
    const tmpDir = mkdtempSync(
        join(ROOT, 'src', 'content', 'docs', 'glossary-'),
    );
    const tmpFile = join(tmpDir, 'glossary.mdx');
    writeFileSync(tmpFile, content);
    formatFile(tmpFile);
    const formatted = readFileSync(tmpFile, 'utf-8');
    rmSync(tmpDir, { recursive: true });
    if (formatted !== existing) {
        console.error(
            'src/content/docs/resources/glossary.mdx is out of date.\n' +
                'Run `pnpm generate:glossary` to regenerate it.',
        );
        process.exit(1);
    }
} else {
    writeFileSync(OUTPUT, content);
    formatFile(OUTPUT);
}
